"""Labels for native-language terms; other documents retain explicit EN fallback."""
UI = {
 'fi': ('Suomi', 'Oikeudelliset asiakirjat', 'Tällä sivulla', 'Asiakirjan kieli', 'Yritystiedot', 'Tarkistettava asiakirjaluonnos, 1.10.2026.'),
 'en': ('English', 'Legal documents', 'On this page', 'Document language', 'Company information', 'Document draft for review, 1 October 2026.'),
 'sv': ('Svenska', 'Juridiska dokument', 'På den här sidan', 'Dokumentets språk', 'Företagsuppgifter', 'Utkast för granskning, 1 oktober 2026.'),
 'no': ('Norsk', 'Juridiske dokumenter', 'På denne siden', 'Dokumentets språk', 'Selskapsopplysninger', 'Utkast til gjennomgang, 1. oktober 2026.'),
 'da': ('Dansk', 'Juridiske dokumenter', 'På denne side', 'Dokumentets sprog', 'Virksomhedsoplysninger', 'Udkast til gennemgang, 1. oktober 2026.'),
 'de': ('Deutsch', 'Rechtliche Dokumente', 'Auf dieser Seite', 'Sprache des Dokuments', 'Unternehmensangaben', 'Entwurf zur Prüfung, 1. Oktober 2026.'),
 'nl': ('Nederlands', 'Juridische documenten', 'Op deze pagina', 'Taal van het document', 'Bedrijfsgegevens', 'Concept ter beoordeling, 1 oktober 2026.'),
 'fr': ('Français', 'Documents juridiques', 'Sur cette page', 'Langue du document', 'Informations sur la société', 'Projet à vérifier, 1er octobre 2026.'),
 'es': ('Español', 'Documentos legales', 'En esta página', 'Idioma del documento', 'Datos de la empresa', 'Borrador para revisión, 1 de octubre de 2026.'),
 'it': ('Italiano', 'Documenti legali', 'In questa pagina', 'Lingua del documento', 'Informazioni societarie', 'Bozza da verificare, 1 ottobre 2026.'),
 'pt': ('Português', 'Documentos legais', 'Nesta página', 'Idioma do documento', 'Dados da empresa', 'Minuta para revisão, 1 de outubro de 2026.'),
 'pl': ('Polski', 'Dokumenty prawne', 'Na tej stronie', 'Język dokumentu', 'Dane firmy', 'Projekt do weryfikacji, 1 października 2026 r.'),
 'et': ('Eesti', 'Õigusdokumendid', 'Sellel lehel', 'Dokumendi keel', 'Ettevõtte andmed', 'Läbivaatamiseks mõeldud eelnõu, 1. oktoober 2026.'),
 'lv': ('Latviešu', 'Juridiskie dokumenti', 'Šajā lapā', 'Dokumenta valoda', 'Uzņēmuma informācija', 'Projekts pārskatīšanai, 2026. gada 1. oktobris.'),
 'lt': ('Lietuvių', 'Teisiniai dokumentai', 'Šiame puslapyje', 'Dokumento kalba', 'Įmonės informacija', 'Projektas peržiūrai, 2026 m. spalio 1 d.'),
}
TITLES = {
 'fi': ('Käyttöehdot', 'Tietosuojaseloste', 'Tietojen ja tilin poistaminen', 'Ostoehdot', 'World Rank -säännöt', 'Evästeet ja sivuston tietosuoja'),
 'en': ('Terms of use', 'Privacy notice', 'Delete your data or account', 'Purchase terms', 'World Rank rules', 'Cookies and website privacy'),
 'sv': ('Användarvillkor', 'Integritetsinformation', 'Radera uppgifter eller konto', 'Köpvillkor', 'World Rank-regler', 'Kakor och webbplatsens integritet'),
 'no': ('Bruksvilkår', 'Personvernerklæring', 'Slett data eller konto', 'Kjøpsvilkår', 'World Rank-regler', 'Informasjonskapsler og personvern'),
 'da': ('Brugsvilkår', 'Privatlivspolitik', 'Slet data eller konto', 'Købsvilkår', 'World Rank-regler', 'Cookies og hjemmesidens privatliv'),
 'de': ('Nutzungsbedingungen', 'Datenschutzhinweise', 'Daten oder Konto löschen', 'Kaufbedingungen', 'World Rank-Regeln', 'Cookies und Website-Datenschutz'),
 'nl': ('Gebruiksvoorwaarden', 'Privacyverklaring', 'Gegevens of account verwijderen', 'Aankoopvoorwaarden', 'World Rank-regels', 'Cookies en websiteprivacy'),
 'fr': ('Conditions d’utilisation', 'Politique de confidentialité', 'Supprimer les données ou le compte', 'Conditions d’achat', 'Règles World Rank', 'Cookies et confidentialité du site'),
 'es': ('Condiciones de uso', 'Aviso de privacidad', 'Eliminar datos o cuenta', 'Condiciones de compra', 'Reglas de World Rank', 'Cookies y privacidad del sitio'),
 'it': ('Condizioni d’uso', 'Informativa sulla privacy', 'Eliminazione dei dati o dell’account', 'Condizioni di acquisto', 'Regole di World Rank', 'Cookie e privacy del sito'),
 'pt': ('Condições de utilização', 'Política de privacidade', 'Eliminar dados ou conta', 'Condições de compra', 'Regras do World Rank', 'Cookies e privacidade do site'),
 'pl': ('Warunki użytkowania', 'Informacja o prywatności', 'Usuwanie danych lub konta', 'Warunki zakupu', 'Zasady World Rank', 'Pliki cookie i prywatność witryny'),
 'et': ('Kasutustingimused', 'Privaatsusteade', 'Andmete või konto kustutamine', 'Ostutingimused', 'World Ranki reeglid', 'Küpsised ja veebisaidi privaatsus'),
 'lv': ('Lietošanas noteikumi', 'Privātuma paziņojums', 'Datu vai konta dzēšana', 'Pirkuma noteikumi', 'World Rank noteikumi', 'Sīkdatnes un vietnes privātums'),
 'lt': ('Naudojimo sąlygos', 'Privatumo pranešimas', 'Duomenų ar paskyros ištrynimas', 'Pirkimo sąlygos', 'World Rank taisyklės', 'Slapukai ir svetainės privatumas'),
}
NOTICES = {
 'sv': 'Det här dokumentet finns på finska och engelska. Nedan visas den engelska versionen.',
 'no': 'Dette dokumentet finnes på finsk og engelsk. Nedenfor vises den engelske versjonen.',
 'da': 'Dette dokument findes på finsk og engelsk. Nedenfor vises den engelske version.',
 'de': 'Dieses Dokument ist auf Finnisch und Englisch verfügbar. Unten steht die englische Fassung.',
 'nl': 'Dit document is beschikbaar in het Fins en Engels. Hieronder staat de Engelse versie.',
 'fr': 'Ce document est disponible en finnois et en anglais. La version anglaise figure ci-dessous.',
 'es': 'Este documento está disponible en finés e inglés. A continuación se muestra la versión inglesa.',
 'it': 'Questo documento è disponibile in finlandese e inglese. Di seguito è riportata la versione inglese.',
 'pt': 'Este documento está disponível em finlandês e inglês. Abaixo encontra-se a versão inglesa.',
 'pl': 'Ten dokument jest dostępny po fińsku i angielsku. Poniżej znajduje się wersja angielska.',
 'et': 'See dokument on saadaval soome ja inglise keeles. Allpool on ingliskeelne versioon.',
 'lv': 'Šis dokuments ir pieejams somu un angļu valodā. Zemāk ir angļu valodas versija.',
 'lt': 'Šis dokumentas pateikiamas suomių ir anglų kalbomis. Toliau rodoma versija anglų kalba.',
}
